In [11]:
## Matematyka w uczeniu głębokim

### Zadanie 1
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a: ", a)
print("b: ", b)
## Typ danych
print("Typ danych: ", a.dtype)

## Wymiar
print("Wymiar: ", a.shape)

## Ilość wymiarów
print("Ilość wymiarów: ", a.ndim)
## Typ 
print("Typ: ", type(a))


### Operacje na tensorze
print("Operacje na tensorze")
## Dodawanie
print("Dodawanie")
c = a + b
print(c)
## Mnożenie
print("Mnożenie")
d = a * b
print(d)
## Mnożenie macierzowe
print("Mnożenie macierzowe")
e = np.dot(a, b)
print(e)
## Slicing
print("Slicing")
print(a[1:3])
print(a[1:])
## Reshape
print("Reshape")
print(a.reshape(3, 1))
## Broadcasting
print("Broadcasting")
print(a + 1)




a:  [1 2 3]
b:  [4 5 6]
Typ danych:  int32
Wymiar:  (3,)
Ilość wymiarów:  1
Typ:  <class 'numpy.ndarray'>
Operacje na tensorze
Dodawanie
[5 7 9]
Mnożenie
[ 4 10 18]
Mnożenie macierzowe
32
Slicing
[2 3]
[2 3]
Reshape
[[1]
 [2]
 [3]]
Broadcasting
[2 3 4]
